name: Compile JSX to JSXBIN

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download ExtendScript Toolkit
      run: |
        $url = "https://github.com/Adobe-CEP/CEP-Resources/raw/master/ExtendScript-Toolkit/AdobeExtendScriptToolkit_4_LS22.exe"
        $output = "$env:TEMP\ESTK_Installer.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
      shell: powershell

    - name: Install ExtendScript Toolkit
      run: |
        Start-Process -FilePath "$env:TEMP\ESTK_Installer.exe" -ArgumentList "/S" -Wait
      shell: powershell

    - name: Compile JSX to JSXBIN
      run: |
        $estkExe = "C:\Program Files (x86)\Adobe\Adobe ExtendScript Toolkit CC\ExtendScript Toolkit.exe"
        $jsxFile = "bpmmarker.jsx"
        $jsxbinFile = "bpmmarker.jsxbin"
        
        & $estkExe -cmd "$jsxFile" "var f=new File('$jsxbinFile');f.open('w');f.write(app.compile(File('$jsxFile')).toSource());f.close();"
      shell: powershell

    - name: Upload JSXBIN artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-script
        path: bpmmarker.jsxbin