name: Compile JSX to JSXBIN

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up ExtendScript Toolkit
      run: |
        $url = "https://raw.githubusercontent.com/Adobe-CEP/CEP-Resources/master/ExtendScript-Toolkit/4.0/ExtendScript%20Toolkit%20CS6.zip"
        $output = "$env:TEMP\ESTK.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath $env:TEMP\ESTK
      shell: powershell

    - name: Compile JSX to JSXBIN
      run: |
        $estkExe = "$env:TEMP\ESTK\ExtendScript Toolkit CS6\ExtendScript Toolkit.exe"
        $jsxFile = "path\to\your\script.jsx"
        $jsxbinFile = "path\to\output\script.jsxbin"
        
        & $estkExe -cmd "$jsxFile" "var f=new File('$jsxbinFile');f.open('w');f.write(app.compile(File('$jsxFile')).toSource());f.close();"
      shell: powershell

    - name: Upload JSXBIN artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-script
        path: path\to\output\script.jsxbin
